-- 1. Create Categories Table
CREATE TABLE IF NOT EXISTS public.restaurant_categories (
    id TEXT PRIMARY KEY,
    label_fr TEXT NOT NULL,
    is_active BOOLEAN DEFAULT true,
    sort_order INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.restaurant_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    category_id TEXT REFERENCES public.restaurant_categories(id),
    name_fr TEXT NOT NULL,
    description_fr TEXT,
    base_price NUMERIC(10, 2) NOT NULL,
    image_url TEXT,
    prep_time TEXT,
    is_available BOOLEAN DEFAULT true,
    badge TEXT,
    is_featured BOOLEAN DEFAULT false,
    customizable BOOLEAN DEFAULT false,
    customization_json JSONB
);

ALTER TABLE public.restaurant_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.restaurant_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read for categories" ON public.restaurant_categories;
CREATE POLICY "Allow public read for categories" ON public.restaurant_categories FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read for items" ON public.restaurant_items;
CREATE POLICY "Allow public read for items" ON public.restaurant_items FOR SELECT USING (true);

TRUNCATE TABLE public.restaurant_items CASCADE;
TRUNCATE TABLE public.restaurant_categories CASCADE;

INSERT INTO public.restaurant_categories (id, label_fr, sort_order) VALUES
('FastFood', 'Fast Food', 1),
('Plats', 'Plats & Beldi', 2),
('Ftour', 'Ftour (Ptit Déj)', 3),
('Salades', 'Salades', 4),
('Desserts', 'Desserts', 5),
('Boissons', 'Boissons', 6)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.restaurant_items (category_id, name_fr, description_fr, base_price, image_url, prep_time, badge, is_featured, customization_json) VALUES
('FastFood', 'Pizza Personnalisée', 'Créez votre pizza parfaite avec la pâte et les garnitures de votre choix.', 20, 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800', '15 min', 'Populaire', true, '{"type":{"label":"Recette","type":"radio","options":[{"id":"marg","label":"Margerite","price":0},{"id":"veg","label":"Végétarienne","price":0},{"id":"viande","label":"Viande Hachée","price":10},{"id":"dinde","label":"Dinde","price":10},{"id":"4from","label":"4 Fromages","price":10},{"id":"kabab","label":"Kabab","price":10},{"id":"fruit","label":"Fruit de Mér","price":15},{"id":"4saisons","label":"4 Saisons","price":15},{"id":"dindefume","label":"Dinde Fumé","price":15}],"default":"marg"},"taille":{"label":"Taille","type":"radio","options":[{"id":"P","label":"Petite (P)","price":0},{"id":"M","label":"Moyenne (M)","price":10},{"id":"G","label":"Grande (G)","price":20}],"default":"P"}}'::jsonb),
('FastFood', 'Tacos Sur Mesure', 'Votre Tacos avec frites et sauce fromagère maison.', 30, '/image/taxos.jpeg', '10 min', 'Bestseller', true, '{"viande":{"label":"Choix Viande","type":"radio","options":[{"id":"viande","label":"Viande Hachée","price":0},{"id":"dinde","label":"Dinde","price":0},{"id":"mixte","label":"Mixte","price":5},{"id":"nuggets","label":"Nuggets","price":10},{"id":"fruitmer","label":"Fruit de Mer","price":15}],"default":"dinde"},"taille":{"label":"Taille du Tacos","type":"radio","options":[{"id":"M","label":"Taille M","price":0},{"id":"L","label":"Taille L","price":10},{"id":"XL","label":"Taille XL","price":20}],"default":"M"},"gratine":{"label":"Supplément Gratiné","type":"radio","options":[{"id":"non","label":"Normal (Non Gratiné)","price":0},{"id":"grat_m","label":"Gratiné M","price":5},{"id":"grat_l","label":"Gratiné L","price":7},{"id":"grat_xl","label":"Gratiné XL","price":10}],"default":"non"},"sauce":{"label":"Sauces internes (Max 2)","type":"checkbox","options":[{"id":"alg","label":"Algérienne"},{"id":"sam","label":"Samourai"},{"id":"and","label":"Andalouse"},{"id":"big","label":"Biggy"},{"id":"ketchup","label":"Ketchup"}]},"supplements":{"label":"Suppléments","type":"checkbox","options":[{"id":"frites","label":"Frites","price":8},{"id":"fromage","label":"Fromage","price":3},{"id":"oeuf","label":"Oeuf","price":3},{"id":"nuggets","label":"1 Nugget","price":4},{"id":"crabe","label":"Crabe","price":5}]}}'::jsonb),
('FastFood', 'Burger Maison', 'Steak haché de boeuf, salade, tomate, oignons, sauce burger.', 20, 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800', '10 min', NULL, false, '{"type":{"label":"Type de Burger","type":"radio","options":[{"id":"burger","label":"Hamburger","price":0},{"id":"cheese","label":"Cheese Burger","price":5},{"id":"chicken","label":"Chicken Burger","price":10},{"id":"american","label":"American Burger","price":15}],"default":"burger"},"combo":{"label":"Formule Menu","type":"radio","options":[{"id":"seul","label":"Seul","price":0},{"id":"menu","label":"Menu (Frites + Boisson)","price":15}],"default":"seul"},"supplements":{"label":"Suppléments","type":"checkbox","options":[{"id":"frites","label":"Frites","price":8},{"id":"fromage","label":"Fromage","price":3},{"id":"oeuf","label":"Oeuf","price":3},{"id":"nuggets","label":"1 Nugget","price":4},{"id":"crabe","label":"Crabe","price":5}]}}'::jsonb),
('FastFood', 'Panini Pressé', 'Pain ciabatta, fromage fondant, garniture au choix.', 15, '/image/panini.jpeg', '5 min', NULL, false, '{"viande":{"label":"Garniture","type":"radio","options":[{"id":"thon","label":"Thon","price":0},{"id":"viande","label":"Viande Hachée","price":5},{"id":"dinde","label":"Dinde","price":5},{"id":"mixte","label":"Mixte","price":10},{"id":"fruitmer","label":"Fruits De Mer","price":10},{"id":"nuggets","label":"Nuggets","price":10},{"id":"cordon","label":"Cordon Bleu","price":10}],"default":"thon"},"combo":{"label":"Formule Menu","type":"radio","options":[{"id":"seul","label":"Seul","price":0},{"id":"menu","label":"Menu (Frites + Boisson)","price":15}],"default":"seul"}}'::jsonb),
('FastFood', 'Sandwich Classique', 'Baguette croustillante, frites, salade, garniture au choix.', 10, 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800', '5 min', NULL, false, '{"viande":{"label":"Garniture","type":"radio","options":[{"id":"normal","label":"Normal (Sans viande)","price":0},{"id":"froid","label":"Froid (Cachir/Fromage)","price":3},{"id":"thon","label":"Thon","price":5},{"id":"viande","label":"Viande Hachée","price":10},{"id":"dinde","label":"Dinde","price":10},{"id":"mixte","label":"Mixte","price":15},{"id":"fruitmer","label":"Fruits De Mer","price":15}],"default":"viande"},"combo":{"label":"Formule Menu","type":"radio","options":[{"id":"seul","label":"Seul","price":0},{"id":"menu","label":"Menu (Frites + Boisson)","price":15}],"default":"seul"}}'::jsonb),
('FastFood', 'Sandwich Pain Maison', 'Notre spécialité pain maison extra moelleux.', 30, 'https://images.unsplash.com/photo-1553909489-cd47cebeefa9?w=800', '10 min', 'Signature', false, '{"viande":{"label":"Spécialité","type":"radio","options":[{"id":"chiken","label":"Chiken","price":0},{"id":"foud","label":"Foud Paris","price":0},{"id":"tandoori","label":"Chiken Tandoori","price":0},{"id":"mixparis","label":"Mix Paris","price":0},{"id":"mixroyale","label":"Mix Royale","price":0},{"id":"cordon","label":"Cordon Bleu","price":0}],"default":"chiken"},"combo":{"label":"Formule Menu","type":"radio","options":[{"id":"seul","label":"Seul","price":0},{"id":"menu","label":"Menu (Frites + Boisson)","price":15}],"default":"seul"}}'::jsonb),
('FastFood', 'Pasticcio & Lasagnes', 'Plats au four gratinés.', 25, 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800', '20 min', 'Gourmand', false, '{"type":{"label":"Type de Plat","type":"radio","options":[{"id":"lasagne","label":"Lasagne","price":0},{"id":"pasticcio","label":"Pasticcio (Macaronis)","price":10}],"default":"pasticcio"},"viande":{"label":"Garniture","type":"radio","options":[{"id":"dinde","label":"Dinde","price":0},{"id":"viande","label":"Viande Hachée","price":0},{"id":"mixte","label":"Mixte","price":5},{"id":"fruitmer","label":"Fruit de Mer","price":10},{"id":"kabab","label":"Kabab","price":10}],"default":"viande"}}'::jsonb),
('FastFood', 'Shawarma & Cheese Naan', 'Spécialités orientales, pain libanais ou indien au fromage.', 25, 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800', '5 min', NULL, false, '{"type":{"label":"Type de Pain","type":"radio","options":[{"id":"shawarma","label":"Shawarma Syrien","price":0},{"id":"naan","label":"Cheese Naan","price":10}],"default":"shawarma"},"viande":{"label":"Garniture","type":"radio","options":[{"id":"normal","label":"Poulet","price":0},{"id":"viande","label":"V.Haché","price":0},{"id":"mixte","label":"Mixte","price":5}],"default":"normal"},"combo":{"label":"Formule Menu","type":"radio","options":[{"id":"seul","label":"Seul","price":0},{"id":"menu","label":"Menu (Frites + Boisson)","price":15}],"default":"seul"}}'::jsonb),
('Plats', 'Tajine Marocain', 'Cuit lentement sur charbon (Fekhar).', 35, '/image/tajin.jpeg', '40 min', 'Beldi', true, '{"variant":{"label":"Type de Tajine","type":"radio","options":[{"id":"poulet_citron","label":"Poulet Citron / Dghmira","price":0},{"id":"kefta","label":"Kefta Oeufs (Sauce Tomate)","price":0},{"id":"legume","label":"Légumes (Végétarien)","price":-5},{"id":"viande_pruneau","label":"Viande Pruneaux","price":30}],"default":"poulet_citron"}}'::jsonb),
('Plats', 'Poulet Rôti (Djaj Mhamer)', 'Poulet rôti à la marocaine avec frites et olives.', 40, '/image/djaj m7amar.jpeg', '20 min', NULL, false, '{"portion":{"label":"Portion","type":"radio","options":[{"id":"quart","label":"1/4 Poulet (Individuel)","price":0},{"id":"demi","label":"1/2 Poulet","price":30},{"id":"entier","label":"Poulet Entier (Famille)","price":80}],"default":"quart"}}'::jsonb),
('Plats', 'Couscous (Vendredi)', 'Plat traditionnel marocain, servi uniquement le vendredi.', 30, '/image/couscous.jpeg', '30 min', 'Spécialité', false, '{"variant":{"label":"Type","type":"radio","options":[{"id":"poulet","label":"Couscous Poulet","price":0},{"id":"viande","label":"Couscous Viande","price":20}],"default":"poulet"}}'::jsonb),
('Plats', 'Pâtes', 'Spaghetti ou Penne servis avec votre sauce préférée.', 30, '/image/les pate.jpeg', '15 min', NULL, false, '{"sauce":{"label":"Recette","type":"radio","options":[{"id":"bolo","label":"Bolognaise","price":0},{"id":"dinde","label":"Dinde Fumé & Crème Fraîche","price":5},{"id":"fruitmer","label":"Fruits de Mer","price":10}],"default":"bolo"},"type":{"label":"Type de Pâtes","type":"radio","options":[{"id":"penne","label":"Penne"},{"id":"spag","label":"Spaghetti"}],"default":"penne"}}'::jsonb),
('Ftour', 'Omelette', 'Œufs de ferme préparés à votre goût.', 15, '/image/Omelette.jpeg', '10 min', NULL, false, '{"variant":{"label":"Type","type":"radio","options":[{"id":"nature","label":"Nature","price":0},{"id":"fromage","label":"Fromage","price":5},{"id":"khlii","label":"Khliî (Viande séchée)","price":10}],"default":"nature"}}'::jsonb),
('Ftour', 'Ftour Complet', 'Petit déjeuner complet traditionnel.', 35, '/image/ftor complet.jpeg', '15 min', NULL, false, NULL),
('Ftour', 'Crêpes & Galettes Chaudes', 'Assortiment de Baghrir, Msamen, Harcha.', 10, '/image/msmn o 7rcha.jpeg', '5 min', NULL, false, '{"accompagnement":{"label":"Accompagnements","type":"checkbox","options":[{"id":"miel","label":"Miel & Beurre","price":2},{"id":"amlou","label":"Amlou (Amandes & Argan)","price":5},{"id":"nutella","label":"Nutella","price":5}]}}'::jsonb),
('Salades', 'Salade Fraîche', 'Légumes frais de saison.', 25, 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800', '10 min', NULL, false, '{"type":{"label":"Variété","type":"radio","options":[{"id":"nicoise","label":"Niçoise","price":0},{"id":"mexicaine","label":"Mexicaine","price":0},{"id":"cesar","label":"César","price":10},{"id":"paris","label":"Paris","price":15}],"default":"nicoise"}}'::jsonb),
('Boissons', 'Jus Frais', 'Pressé minute, 100% fruits.', 10, 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=800', '5 min', NULL, false, '{"fruit":{"label":"Fruit","type":"radio","options":[{"id":"orange","label":"D''orange","price":0},{"id":"citron","label":"De Citron","price":0},{"id":"pomme","label":"De pomme","price":0},{"id":"banane","label":"De Banane","price":0},{"id":"tropical","label":"Tropical","price":0},{"id":"avocat","label":"De avocat","price":6},{"id":"panache","label":"Panaché (Orange)","price":8}],"default":"orange"},"sucre":{"label":"Sucre","type":"radio","options":[{"id":"avec","label":"Avec Sucre"},{"id":"sans","label":"Sans Sucre"}],"default":"avec"}}'::jsonb),
('Boissons', 'Cafétéria', 'Boissons chaudes premium.', 10, 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800', '5 min', NULL, false, '{"boisson":{"label":"Choix","type":"radio","options":[{"id":"cafe","label":"Café Espresso","price":0},{"id":"lait","label":"Lait Chaud","price":0},{"id":"nousnous","label":"Nouss Nouss","price":0},{"id":"the","label":"Thé à la Menthe","price":5}],"default":"cafe"}}'::jsonb),
('Boissons', 'Soda & Eau', 'Boissons fraîches.', 5, 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=800', '2 min', NULL, false, '{"boisson":{"label":"Choix","type":"radio","options":[{"id":"eau_p","label":"Eau Minérale (Petite)","price":0},{"id":"eau_g","label":"Eau 50 Cl","price":3},{"id":"coca","label":"Soda Canette (Coca, etc.)","price":5}],"default":"eau_p"}}'::jsonb),
('Desserts', 'Salade de fruit', 'Cocktail de fruits de saison fraîchement coupés.', 40, 'https://images.unsplash.com/photo-1490474418585-ba9f528d2981?w=800', '10 min', 'Frais', true, NULL),
('Desserts', 'Flan Amlou', 'Flan onctueux parfumé à la pâte d''Amlou.', 15, 'https://images.unsplash.com/photo-1590080876477-d923a1a3debb?w=800', '5 min', 'Local', false, NULL),
('Desserts', 'Za3za3', 'Cocktail avocat, fruits, crème et fruits secs.', 25, 'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=800', '10 min', 'Énergie', true, NULL)
;